# Generated by Django 3.2.5 on 2022-03-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDatas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('usernameAccount', models.CharField(max_length=100, unique=True)),
                ('emailAccount', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('isActive', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('walletAddress', models.CharField(max_length=100)),
                ('evaluation', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
