# Generated by Django 3.2.5 on 2022-03-13 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprojectapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromAddress', models.CharField(max_length=100)),
                ('toAddress', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=4)),
                ('token', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('userData', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprojectapp.userdatas')),
            ],
        ),
    ]
