# Generated by Django 3.2.5 on 2022-03-13 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprojectapp', '0003_fundingprojects'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeLists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likeOrNot', models.BooleanField(blank=True)),
                ('fundingProject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprojectapp.fundingprojects')),
                ('userData', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprojectapp.userdatas')),
            ],
        ),
        migrations.AddField(
            model_name='fundingprojects',
            name='userLikeList',
            field=models.ManyToManyField(through='userprojectapp.LikeLists', to='userprojectapp.UserDatas'),
        ),
    ]
