# Generated by Django 3.2.5 on 2022-03-13 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprojectapp', '0004_auto_20220314_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundingprojects',
            name='userLikeList',
            field=models.ManyToManyField(related_name='userLike', through='userprojectapp.LikeLists', to='userprojectapp.UserDatas'),
        ),
        migrations.CreateModel(
            name='FundingShares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share', models.DecimalField(decimal_places=4, max_digits=4)),
                ('fundingProject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprojectapp.fundingprojects')),
                ('userData', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprojectapp.userdatas')),
            ],
        ),
        migrations.AddField(
            model_name='fundingprojects',
            name='userFundingShare',
            field=models.ManyToManyField(related_name='userFunding', through='userprojectapp.FundingShares', to='userprojectapp.UserDatas'),
        ),
    ]
