# Generated by Django 3.2.5 on 2022-03-13 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprojectapp', '0005_auto_20220314_0156'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fundingprojects',
            table='funding_projects',
        ),
        migrations.AlterModelTable(
            name='fundingshares',
            table='funding_shares',
        ),
        migrations.AlterModelTable(
            name='likelists',
            table='like_lists',
        ),
        migrations.AlterModelTable(
            name='transferlogs',
            table='transfer_logs',
        ),
        migrations.AlterModelTable(
            name='userdatas',
            table='user_datas',
        ),
    ]
